### PR TITLE
Feature: Prefetching

### PR DESCRIPTION
**Pull request by ddfreiling**
Implemented these pipeline methods:

- `prefetchToDiskCache: Promise<void>`
- `prefetchToMemoryCache: Promise<void>`
- `isInDiskCache: boolean`

### CODE REVIEW

**Comment by farfromrefug** [comment]
@ddfreiling amazing thanks a lot!
Did you test it well? Don't really have time to test.
Can i release? ;)

**Comment by ddfreiling** [comment]
No problem @farfromrefug. Tested it a lot with the angular demo, and it seems to work well and handle errors correctly. I would definitely prefer you do some cursory testing before releasing it.

The only thing which bugs me, is that Fresco's `prefetchToBitmapCache` also seems to store in the disk cache, while it does not on iOS.

This could be "smoothed out" by having iOS store to both caches too.
Alternatively we could just add a new `prefetchToCaches`, so that all 3 things are possible.

**Comment by ddfreiling** [comment]
@farfromrefug Any plan for when you'll release this?

**Comment by farfromrefug** [comment]
@ddfreiling may be next week if that s ok. Need to test it but dont really have time right now. Big release time for an app ;)

**Comment by ddfreiling** [comment]
@farfromrefug that's perfectly fine, good luck with the big release :)

**Pull request merged**
